export const CLEAR_WEATHERS = 'CLEAR_WEATHERS'
export const GET_WEATHERS = 'GET_WEATHERS'
export const GET_WEATHER = 'GET_WEATHER'
export const SET_LOADING = 'SET_LOADING'
export const SET_STOP_LOADING = 'SET_STOP_LOADING'
export const SELECT_CITY_INDEX = 'SELECT_CITY_INDEX'
export const SELECT_CITY_ONE_INDEX = 'SELECT_CITY_ONE_INDEX'


